# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DemoLeaderBoardNative-desktop' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DemoLeaderBoardNative-desktop

end

target 'DemoLeaderBoardNative-mobile' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DemoLeaderBoardNative-mobile
  pod 'FBAudienceNetwork'
end
